export const staffList: any[] = [
    {
        Code: 'H00001',
        Position: 'Giám đốc',
        FirstName: 'Huỳnh',
        MiddleName: 'Khánh',
        LastName: 'Luân',
        Department: 'Ban giám đốc',
        LocationName: 'Văn phòng 40',
        Gender: 'Nam',
        Birth: '01/01/2010',
        TypeOfStaff: 'Nhân viên chính thức',
        Status: 'Đang làm việc',
    },
    {
        Code: 'H00001',
        Position: 'Giám đốc',
        FirstName: 'Huỳnh',
        MiddleName: 'Khánh',
        LastName: 'Luân',
        Department: 'Ban giám đốc',
        LocationName: 'Văn phòng 40',
        Gender: 'Nam',
        Birth: '01/01/2010',
        TypeOfStaff: 'Nhân viên chính thức',
        Status: 'Đang làm việc',
    },
    {
        Code: 'H00001',
        Position: 'Giám đốc',
        FirstName: 'Huỳnh',
        MiddleName: 'Khánh',
        LastName: 'Luân',
        Department: 'Ban giám đốc',
        LocationName: 'Văn phòng 40',
        Gender: 'Nam',
        Birth: '01/01/2010',
        TypeOfStaff: 'Nhân viên chính thức',
        Status: 'Đang làm việc',
    },
    {
        Code: 'H00001',
        Position: 'Giám đốc',
        FirstName: 'Huỳnh',
        MiddleName: 'Khánh',
        LastName: 'Luân',
        Department: 'Ban giám đốc',
        LocationName: 'Văn phòng 40',
        Gender: 'Nam',
        Birth: '01/01/2010',
        TypeOfStaff: 'Nhân viên chính thức',
        Status: 'Đang làm việc',
    },
    {
        Code: 'H00001',
        Position: 'Giám đốc',
        FirstName: 'Huỳnh',
        MiddleName: 'Khánh',
        LastName: 'Luân',
        Department: 'Ban giám đốc',
        LocationName: 'Văn phòng 40',
        Gender: 'Nam',
        Birth: '01/01/2010',
        TypeOfStaff: 'Nhân viên chính thức',
        Status: 'Đang làm việc',
    },
    {
        Code: 'H00001',
        Position: 'Giám đốc',
        FirstName: 'Huỳnh',
        MiddleName: 'Khánh',
        LastName: 'Luân',
        Department: 'Ban giám đốc',
        LocationName: 'Văn phòng 40',
        Gender: 'Nam',
        Birth: '01/01/2010',
        TypeOfStaff: 'Nhân viên chính thức',
        Status: 'Đang làm việc',
    },
    {
        Code: 'H00001',
        Position: 'Giám đốc',
        FirstName: 'Huỳnh',
        MiddleName: 'Khánh',
        LastName: 'Luân',
        Department: 'Ban giám đốc',
        LocationName: 'Văn phòng 40',
        Gender: 'Nam',
        Birth: '01/01/2010',
        TypeOfStaff: 'Nhân viên chính thức',
        Status: 'Đang làm việc',
    },
    {
        Code: 'H00001',
        Position: 'Giám đốc',
        FirstName: 'Huỳnh',
        MiddleName: 'Khánh',
        LastName: 'Luân',
        Department: 'Ban giám đốc',
        LocationName: 'Văn phòng 40',
        Gender: 'Nam',
        Birth: '01/01/2010',
        TypeOfStaff: 'Nhân viên chính thức',
        Status: 'Đang làm việc',
    },
    {
        Code: 'H00001',
        Position: 'Giám đốc',
        FirstName: 'Huỳnh',
        MiddleName: 'Khánh',
        LastName: 'Luân',
        Department: 'Ban giám đốc',
        LocationName: 'Văn phòng 40',
        Gender: 'Nam',
        Birth: '01/01/2010',
        TypeOfStaff: 'Nhân viên chính thức',
        Status: 'Đang làm việc',
    },
    {
        Code: 'H00001',
        Position: 'Giám đốc',
        FirstName: 'Huỳnh',
        MiddleName: 'Khánh',
        LastName: 'Luân',
        Department: 'Ban giám đốc',
        LocationName: 'Văn phòng 40',
        Gender: 'Nam',
        Birth: '01/01/2010',
        TypeOfStaff: 'Nhân viên chính thức',
        Status: 'Đang làm việc',
    },
    {
        Code: 'H00001',
        Position: 'Giám đốc',
        FirstName: 'Huỳnh',
        MiddleName: 'Khánh',
        LastName: 'Luân',
        Department: 'Ban giám đốc',
        LocationName: 'Văn phòng 40',
        Gender: 'Nam',
        Birth: '01/01/2010',
        TypeOfStaff: 'Nhân viên chính thức',
        Status: 'Đang làm việc',
    },
    {
        Code: 'H00001',
        Position: 'Giám đốc',
        FirstName: 'Huỳnh',
        MiddleName: 'Khánh',
        LastName: 'Luân',
        Department: 'Ban giám đốc',
        LocationName: 'Văn phòng 40',
        Gender: 'Nam',
        Birth: '01/01/2010',
        TypeOfStaff: 'Nhân viên chính thức',
        Status: 'Đang làm việc',
    },
    {
        Code: 'H00001',
        Position: 'Giám đốc',
        FirstName: 'Huỳnh',
        MiddleName: 'Khánh',
        LastName: 'Luân',
        Department: 'Ban giám đốc',
        LocationName: 'Văn phòng 40',
        Gender: 'Nam',
        Birth: '01/01/2010',
        TypeOfStaff: 'Nhân viên chính thức',
        Status: 'Đang làm việc',
    },
    {
        Code: 'H00001',
        Position: 'Giám đốc',
        FirstName: 'Huỳnh',
        MiddleName: 'Khánh',
        LastName: 'Luân',
        Department: 'Ban giám đốc',
        LocationName: 'Văn phòng 40',
        Gender: 'Nam',
        Birth: '01/01/2010',
        TypeOfStaff: 'Nhân viên chính thức',
        Status: 'Đang làm việc',
    },
];
