export const items = [
    {
        text: 'KHUYẾN MÃI',
        icon: 'k-i-inbox',
        expanded: false,
        children: false,
        selected: false,
        level: 0,
        id: 1,
    },
    {
        text: 'CƠ CẤU TỔ CHỨC',
        icon: 'k-i-inbox',
        expanded: false,
        children: true,
        selected: false,
        level: 0,
        id: 2,
    },
    {
        text: 'QUẢN LÝ BANNER',
        icon: 'k-i-inbox',
        expanded: false,
        children: false,
        selected: false,
        level: 0,
        id: 3,
    },
    {
        text: 'CHÍNH SÁCH',
        icon: 'k-i-inbox',
        expanded: false,
        children: true,
        selected: false,
        level: 0,
        id: 4,
    },
    {
        text: 'BÁO CÁO EXCEL',
        icon: 'k-i-inbox',
        expanded: false,
        children: false,
        selected: false,
        level: 0,
        id: 5,
    },
    {
        text: 'HỒ SƠ NHÂN SỰ',
        icon: 'k-i-inbox',
        expanded: false,
        children: true,
        selected: true,
        level: 0,
        id: 6,
    },

    {
        text: 'Coupon',
        children: false,
        selected: true,
        level: 1,
        parentId: 4,
    },
    {
        text: 'PolicyX1',
        children: false,
        selected: false,
        level: 1,
        parentId: 4,
    },
    {
        text: 'PolicyX2',
        children: false,
        selected: false,
        level: 1,
        parentId: 4,
    },
    {
        text: 'PolicyX3',
        children: false,
        selected: false,
        level: 1,
        parentId: 4,
    },
    {
        text: 'Cơ cấu tổ chức',
        children: false,
        selected: false,
        level: 1,
        parentId: 2,
    },
    {
        text: 'Điểm làm việc',
        children: false,
        selected: false,
        level: 1,
        parentId: 2,
    },
    {
        text: 'Danh sách nhân sự',
        children: false,
        selected: true,
        level: 1,
        parentId: 6,
    },
];
